### DATA PROCESSING NOTEBOOK

In [1]:
# Import necessary libraries
import pandas as pd
import os

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import joblib

In [2]:
# Import data
dir_path = os.path.join(os.path.dirname(os.getcwd()), "data", "processed")
data_path = os.path.join(dir_path, "interpolated_data.xlsx")
df = pd.read_excel(data_path)
df.shape

(300, 4)

In [3]:
df.head(10)

        1/T  ln strain rate  Strain    σ/σmax
0  0.000756       -2.302585   0.100  0.172481
1  0.000756       -2.302585   0.125  0.199383
2  0.000756       -2.302585   0.150  0.226284
3  0.000756       -2.302585   0.175  0.253186
4  0.000756       -2.302585   0.200  0.280087
5  0.000756       -2.302585   0.225  0.292336
6  0.000756       -2.302585   0.250  0.304584
7  0.000756       -2.302585   0.275  0.316833
8  0.000756       -2.302585   0.300  0.329081
9  0.000756       -2.302585   0.325  0.334996

In [4]:
df.describe()

              1/T  ln strain rate      Strain      σ/σmax
count  300.000000      300.000000  300.000000  300.000000
mean     0.000786        0.677013    0.400000    0.659757
std      0.000025        2.009839    0.180579    0.196041
min      0.000756       -2.302585    0.100000    0.172481
25%      0.000756       -0.575646    0.250000    0.510209
50%      0.000786        1.151293    0.400000    0.677710
75%      0.000818        2.403951    0.550000    0.815900
max      0.000818        2.708050    0.700000    1.000000

In [5]:
df.isnull().sum()

1/T               0
ln strain rate    0
Strain            0
σ/σmax            0
dtype: int64

### DATA SPLITTING

In [6]:
# Splitting the data
X = df.drop(["σ/σmax"], axis = 1)
y = df["σ/σmax"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,shuffle=True)

# Further split it to validation as well
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size = 0.15, random_state=42)

print(f"X_train: {X_train.shape}, y_train: {y_train.shape}")
print(f"X_val: {X_val.shape}, y_val: {y_val.shape}")
print(f"X_test: {X_test.shape}, y_train: {y_test.shape}")

X_train: (204, 3), y_train: (204,)
X_val: (36, 3), y_val: (36,)
X_test: (60, 3), y_train: (60,)

### FEATURE SCALING

In [7]:
# Scaling with min max scaler to follow the normal operating range
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

In [8]:
# Saving the scaler.
joblib.dump(scaler, '../artifacts/scaler.pkl')
print("Scaler saved successfully")
print(f"Feature range after scaling: {scaler.data_range_}")

Scaler saved successfully
Feature range after scaling: [6.18035894e-05 5.01063529e+00 6.00000000e-01]